### ISSUE TITLE
"–" (en-dash) is removed from shortname

### ISSUE THREAD

**Issue by ya-d** [ecampbell/moodle-local_uploadenrolmentmethods#1]
…which leads to "unknown course".
![image](https://user-images.githubusercontent.com/30781876/88235437-2b6f9c80-cc7b-11ea-9b4c-8aea54caee6b.png)

**Comment by ecampbell** [comment]
I have released version 1,3, which uses the standard Moodle CSV import facility, and supports importing files in UTF-8 encoding. The en-dash is saved properly in UTF-8 encoding. I'm not sure, but I think when you save and Excel file as CSV, it uses UTF-8 encoding by default, so the problem should be solved now. You can also now select a delimiter such as tab instead of comma, so support for Excel in other languages is better.
